title: Inahoya Notes
description: Physics Note
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

mathjax: true
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache
