title: Inahoya Notes
description: Physics Note
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache
mathjax: true
# サイドバー設定
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      sidebar:
        nav: "main"
